export default {
  YOUR_EXPERTISE: 'Your Expertise',
  YOUR_EXPERTISE_TITLE: 'Your Expertise',
  EXPERTISE: 'Expertise',
  YOUR_EXPERTISE_DESCRIPTION:
    'Specialization in one particular field helps you get more work! This qualifies you to receive translation projects that correspond with your area of expertise (once you’re approved). Simply indicate any specialization below, keeping in mind this will be verified in your credentials.',
  YES: 'Yes',
  NO: 'No',
  SELECT: 'Select',
  INCLUDE_EXPERTISE: 'Include area of expertise',
  INCLUDE_EXPERTISE_CATEGORY: 'Add an expertise category',
  EXPERTISE_CATEGORY_TYPE: 'Start typing...',
  EXPERTISE_CATEGORY_HELPER_1: 'Click Enter to add your keywords',
  EXPERTISE_CATEGORY_HELPER_2: 'Enter up to 9 more categories',
  EXPERTISE_PICTURE: 'Profile Picture',
  EXPERTISE_PICTURE_UPLOAD: 'Upload profile picture',
  EXPERTISE_PICTURE_DELETE: 'Delete avatar',
  LINKEDIN_TITLE: 'Add a LinkedIn profile URL',
  LINKEDIN_PASTE: 'Paste URL here',
  SOFTWARE_TITLE: 'Any experience working with specialized software?',
  PROFESSIONAL_EXPERIENCE: 'Please write a short description of your professional experience',
  ABOUT_PLACEHOLDER: 'Tell us about yourself',
  ABOUT_HELPER_MIN: 'Minimum characters - 150',
  ABOUT_HELPER_MAX: 'Maximum characters - 5000',
  ABOUT_HELPER_TOO_SHORT:
    'Sorry, your description of professional experience should be at least 150 characters but not more than 5000 characters.',
  LINKEDIN_ERROR: 'Please add a link to your LinkedIn profile, not any other website',
  UPLOAD_LATER: 'Upload later ',
  ADD_NEEDED_INFORMATION: 'Please add the needed information',
};
